DROP TABLE IF EXISTS EMPLOYEE_DETAILS;

CREATE TABLE EMPLOYEE_DETAILS(EMPLOYEEID INT PRIMARY KEY,
   NAME VARCHAR(255),
   DEPARTMENT VARCHAR(100),
   ADDRESS VARCHAR(255),
   EMAILID VARCHAR(100)
);

INSERT INTO EMPLOYEE_DETAILS VALUES(123456, 'Dhanuja', 'Engineering','Bangalore, IN','dhanuja.n@techiebeans.com');